// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2E8Jkw0NGXgbHosMdlmaf5-kAQvmOPxo',
    appId: '1:584112023735:web:ad878bc6e6007d04c90532',
    messagingSenderId: '584112023735',
    projectId: 'listenup-460bd',
    authDomain: 'listenup-460bd.firebaseapp.com',
    storageBucket: 'listenup-460bd.firebasestorage.app',
    measurementId: 'G-JPB3JD0C1R',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtCG5M79B-UMBLnThObsqDHadm3HaHJAc',
    appId: '1:584112023735:ios:73852009bb7fbd69c90532',
    messagingSenderId: '584112023735',
    projectId: 'listenup-460bd',
    storageBucket: 'listenup-460bd.firebasestorage.app',
    iosBundleId: 'com.example.soundApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtCG5M79B-UMBLnThObsqDHadm3HaHJAc',
    appId: '1:584112023735:ios:73852009bb7fbd69c90532',
    messagingSenderId: '584112023735',
    projectId: 'listenup-460bd',
    storageBucket: 'listenup-460bd.firebasestorage.app',
    iosBundleId: 'com.example.soundApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2E8Jkw0NGXgbHosMdlmaf5-kAQvmOPxo',
    appId: '1:584112023735:web:59690cec1f64f3b3c90532',
    messagingSenderId: '584112023735',
    projectId: 'listenup-460bd',
    authDomain: 'listenup-460bd.firebaseapp.com',
    storageBucket: 'listenup-460bd.firebasestorage.app',
    measurementId: 'G-GS631ZXKL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIEB8xaU7aHQ9TeBMCQ5GhbjgLVtswvbg',
    appId: '1:584112023735:android:571b32494fb8384fc90532',
    messagingSenderId: '584112023735',
    projectId: 'listenup-460bd',
    storageBucket: 'listenup-460bd.firebasestorage.app',
  );

}